### ISSUE TITLE
编码错误提示问题改进

### ISSUE THREAD

**Issue by HuangDabao** [qiniu/goplus#141]
目前不同的编码错误类型，错误提示的格式不统一
希望后续改进为，包含错误代码文件、错误代码行数、错误代码原因，统一的错误提示格式

**Comment by insionng** [comment]
是的，希望抛出的错误能精准定位，现在一崩溃就整个栈所有信息都抛出来，信息量实在太大了

**Comment by di3663** [comment]
@xushiwei 

我开始尝试用qlang做模板，发现有些错误提示信息太少了。能给出是哪行都行，比如： vendor/qiniupkg.com/text/tpl.v1/scanner.go 出错提示信息

illegal rune literal

一个模板一千行是比较常见，难找
