### ISSUE TITLE
Why should we name _goprj and _modutil with prefix underscores?

### ISSUE THREAD

**Issue by wangkuiyi** [qiniu/goplus#311]
When I apply the go-vet hook from https://github.com/dnephin/pre-commit-golang/blob/master/.pre-commit-hooks.yaml, these underscores confused go-vet because the package names and import paths don't contain the underscores.

**Comment by xushiwei** [comment]
Name with underscore means to skip this module.

**Comment by wangkuiyi** [comment]
I see. 

Do we have a plan with these two directories? Like removing them or removing the prefix underscores from their names?
