### ISSUE TITLE
关于 qlang -> goplus 的一个过渡

### ISSUE THREAD

**Issue by VillanCh** [qiniu/goplus#354]
在我的项目中，其实已经很高程度集成并应用了 qlang，并把 qlang 做为一个嵌入式语言频繁使用，并且为 qlang 修复了很多未完成的特性和现有的 BUG

现在新的 goplus 出现了，那么我有几个问题希望能得到大佬们的解答

1. goplus 和之前旧版本的 qlang 进行对比，有哪些区别呢？
2. 作为嵌入式语言来说，使用现有的 goplus 来代替 qlang 会有什么注意事项呢？

**Comment by xushiwei** [comment]
老的 qlang 在这里维护：
* https://github.com/xushiwei/qlang
你可以继续使用，不受影响。
goplus 和 qlang 是不同目的的东西，goplus 的目标是 data science。
从语法上的区别来说，goplus 是静态类型语言，和 qlang 最大差别可能在这里。

**Comment by xushiwei** [comment]
另外，从成熟度来说，goplus 还在 alpha 阶段，完成度还没有 qlang 高。所以当前不建议去考虑切换的事情。

**Comment by VillanCh** [comment]
感谢您的回答！我这里决定仍然使用 qlang 作为嵌入式语言，如果 goplus 没有继续做嵌入式语言的打算的话可能也没有办法切到新的版本上吧

**Comment by xushiwei** [comment]
goplus 是支持嵌入式的，现在就可以（可以认真看一下 README.md）。只不过它的确和 qlang 不一样，是一个静态类型语言，这是最大的区别。
