### ISSUE TITLE
Remove filesystem abstraction

### ISSUE THREAD

**Issue by wangkuiyi** [qiniu/goplus#365]
In parse.go there is an abstraction of filesystems:

https://github.com/qiniu/goplus/blob/251e782877a2b357b7cba48dc00fe398d8600ab7/parser/parse.go#L35-L56

I am not sure if we really want this. It looks to me that if the source files are not on the local filesystem, it is the responsibility of FUSE or other filesystem abstraction mechanisms to "mount" them to the local filesystem so that application developers shouldn't need to care about this.

If this is correct, how about we remove this abstraction?

**Comment by xushiwei** [comment]
This is used by our testcases. We use github.com/qiniu/goplus/ast/asttest.NewSingleFileFS to test.
