### ISSUE TITLE
Unexpose IsDir in qrun.go

### ISSUE THREAD

**Issue by wangkuiyi** [qiniu/goplus#366]
The result of `git grep` reveals that qrun.go is the only caller of the function IsDir:

https://github.com/qiniu/goplus/blob/251e782877a2b357b7cba48dc00fe398d8600ab7/cmd/qrun/qrun.go#L91-L97

**Comment by xushiwei** [comment]
Maybe it will be moved to some utilities package one day. I think it is reasonable to expose.
