### ISSUE TITLE
request for more details about the debug

### ISSUE THREAD

**Issue by hsiaosiyuan0** [qiniu/goplus#367]
Hi, 

I find that goplus has two backends: bytecode and go-codegen, I known it could be easy to implement debug in the bytecode mode, just generating something like symbol files and let the VM execution to be suspendable, when it's reaching a breakpoint, reflecting its internal state by relating those generated symbol files. 

I'm curious about how does goplus handle this process when it's in the go-codegen mode, I'd like to learn more about that, any help is appreciated.

**Comment by xushiwei** [comment]
Most symbols are same in goplus and go. So, it will be done by go itself.
