### ISSUE TITLE
How to build binary in package ?

### ISSUE THREAD

**Issue by blueway** [qiniu/goplus#371]
Like `go build` and Support cross compilation

**Comment by xushiwei** [comment]
`qrun` runs Go+ programs as scripts.
`qgo` converts Go+ packages into Go packages.
Both of them don't generate binary. So, build binary (including cross compilation) is same as Go.

**Comment by blueway** [comment]
so the Go+ just translate `gop` to `go` file , the rest of the work need go tools . But my whole Go+ project files were translated into only one `xx__autogen.go` file, and how can i publish my project  as a library? Just publish the `xx__autogen.go` file?

**Comment by xushiwei** [comment]
No, a Go+ package will convert into a Go package (only one `gop_autogen.go`， not a Go+ project (may have many Go+ packages. This is same to a Go+ project).

**Comment by blueway** [comment]
I think it's best to translate each `gop` file to `go` file with the same file name

**Comment by xushiwei** [comment]
Too many autogen-files will disturb Go+ users.
