### ISSUE TITLE
Rename HasUnnamed into HasEntrypoint?

### ISSUE THREAD

**Issue by wangkuiyi** [qiniu/goplus#393]
In type `ast.File` there is a field `HasUnnamed`

https://github.com/qiniu/goplus/blob/960b8428b6a2bba6c28eff3a5cb45c5541a1dffd/ast/ast.go#L998

which, according to the source code in `parser/parse.go`, means if the programmer explicitly defined the entrypoint function `init` or `main`.

Should we rename it into `HasEntrypoint`?

**Comment by xushiwei** [comment]
It seems good. But `HasUnnamed` means `NoEntrypoint` or `HasntEntrypoint`.
