### ISSUE TITLE
There is an error in the code shown

### ISSUE THREAD

**Issue by chenpfeisoo** [qiniu/goplus#398]
![image](https://user-images.githubusercontent.com/18147157/86445493-1327f400-bd45-11ea-9026-6169af9a5984.png)

package main

import (
	. "fmt"
)

func main() {
	a := []float64{1, 2, 3.4}
	Println(a)
}

**Comment by msal4** [comment]
probably because you imported package "fmt" and never used it

**Comment by chenpfeisoo** [comment]
go

**Comment by chenpfeisoo** [comment]
go

```go
package main

import (
  . "fmt"
)

func main() {
a := []float64{1, 2, 3.4}
Println(a)
}
```
in go+
```go
package main
import (
  "github.com/qiniu/goplus/tutorial/14-Using-goplus-in-Go/foo"
)
func main() {
  a := []float64{1, 2, 3.4}
  println(a)
}
```
case sensitive

**Comment by chenpfeisoo** [comment]
The example shows  go, not go+

**Comment by damonchen** [comment]
there are builtin function called println, not the fmt package Println.

**Comment by chenpfeisoo** [comment]
I see. Thank you for your explanation
