### ISSUE TITLE
可以专门出一个goplus的视频教程或者图书吗？

### ISSUE THREAD

**Issue by joyoes** [qiniu/goplus#408]
可以专门出一个goplus的视频教程或者图书吗？

**Comment by JessonChan** [comment]
现在可以看目前工程下的tutorial目录，涵盖了很所有Go+的语法特性。

**Comment by xushiwei** [comment]
已经有一些第三方机构在考虑这事。
当前 Go+ 还在 alpha 阶段，我们当前重心还是保证年底 Go+ 1.0 的发布。
